// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// Q_sparse_cpp
Eigen::SparseMatrix<double> Q_sparse_cpp(double growth, double carry_cap, double move_const, double sigma, double timestep, NumericVector linpoint, int ns, int nt, const Eigen::SparseMatrix<double>& C, const Eigen::SparseMatrix<double>& G, const Eigen::SparseMatrix<double>& CinvG, const Eigen::SparseMatrix<double>& prior_precision);
RcppExport SEXP _INLAloggrowth_Q_sparse_cpp(SEXP growthSEXP, SEXP carry_capSEXP, SEXP move_constSEXP, SEXP sigmaSEXP, SEXP timestepSEXP, SEXP linpointSEXP, SEXP nsSEXP, SEXP ntSEXP, SEXP CSEXP, SEXP GSEXP, SEXP CinvGSEXP, SEXP prior_precisionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type growth(growthSEXP);
    Rcpp::traits::input_parameter< double >::type carry_cap(carry_capSEXP);
    Rcpp::traits::input_parameter< double >::type move_const(move_constSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type timestep(timestepSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type linpoint(linpointSEXP);
    Rcpp::traits::input_parameter< int >::type ns(nsSEXP);
    Rcpp::traits::input_parameter< int >::type nt(ntSEXP);
    Rcpp::traits::input_parameter< const Eigen::SparseMatrix<double>& >::type C(CSEXP);
    Rcpp::traits::input_parameter< const Eigen::SparseMatrix<double>& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const Eigen::SparseMatrix<double>& >::type CinvG(CinvGSEXP);
    Rcpp::traits::input_parameter< const Eigen::SparseMatrix<double>& >::type prior_precision(prior_precisionSEXP);
    rcpp_result_gen = Rcpp::wrap(Q_sparse_cpp(growth, carry_cap, move_const, sigma, timestep, linpoint, ns, nt, C, G, CinvG, prior_precision));
    return rcpp_result_gen;
END_RCPP
}
// mu_sparse_cpp
NumericVector mu_sparse_cpp(double growth, double carry_cap, double move_const, double timestep, NumericVector linpoint, NumericMatrix grad, NumericVector prior_mean, int ns, int nt, const Eigen::SparseMatrix<double>& CinvG);
RcppExport SEXP _INLAloggrowth_mu_sparse_cpp(SEXP growthSEXP, SEXP carry_capSEXP, SEXP move_constSEXP, SEXP timestepSEXP, SEXP linpointSEXP, SEXP gradSEXP, SEXP prior_meanSEXP, SEXP nsSEXP, SEXP ntSEXP, SEXP CinvGSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type growth(growthSEXP);
    Rcpp::traits::input_parameter< double >::type carry_cap(carry_capSEXP);
    Rcpp::traits::input_parameter< double >::type move_const(move_constSEXP);
    Rcpp::traits::input_parameter< double >::type timestep(timestepSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type linpoint(linpointSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type grad(gradSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prior_mean(prior_meanSEXP);
    Rcpp::traits::input_parameter< int >::type ns(nsSEXP);
    Rcpp::traits::input_parameter< int >::type nt(ntSEXP);
    Rcpp::traits::input_parameter< const Eigen::SparseMatrix<double>& >::type CinvG(CinvGSEXP);
    rcpp_result_gen = Rcpp::wrap(mu_sparse_cpp(growth, carry_cap, move_const, timestep, linpoint, grad, prior_mean, ns, nt, CinvG));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_INLAloggrowth_Q_sparse_cpp", (DL_FUNC) &_INLAloggrowth_Q_sparse_cpp, 12},
    {"_INLAloggrowth_mu_sparse_cpp", (DL_FUNC) &_INLAloggrowth_mu_sparse_cpp, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_INLAloggrowth(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
