# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Q_sparse_cpp <- function(growth, carry_cap, move_const, sigma, timestep, linpoint, ns, nt, C, G, CinvG, prior_precision) {
    .Call('_INLAloggrowth_Q_sparse_cpp', PACKAGE = 'INLAloggrowth', growth, carry_cap, move_const, sigma, timestep, linpoint, ns, nt, C, G, CinvG, prior_precision)
}

mu_sparse_cpp <- function(growth, carry_cap, move_const, timestep, linpoint, grad, prior_mean, ns, nt, CinvG) {
    .Call('_INLAloggrowth_mu_sparse_cpp', PACKAGE = 'INLAloggrowth', growth, carry_cap, move_const, timestep, linpoint, grad, prior_mean, ns, nt, CinvG)
}

